#!/usr/bin/env node

var program = require('commander');

program
  .option('-v, --verbose', 'Show verbose errors and results')
  .option('-p, --production', 'Migrates for production env')
  .option('-s, --staging', 'Migrate for staging env')
  .option('-e, --env <flag>', 'Specify custom environment flag for migration')
  .parse(process.argv)

let env = 'development'

if(program.production){
  env = 'production'
}else if(program.staging){
  env = 'staging'
}else if(program.env){
  env = program.env
}

const knex = require('knex')(require('../knexfile.js')[env])
const schema = require('../schema.js')

console.log("\x1b[1m")
console.log('[ape] Migrating tables...')
console.log()

schema.up(knex)
  .then(res => {
    console.log("\x1b[32m")
    console.log('[ape] Migration finished successfully')

    if(program.verbose)
      console.log(res)

    console.log()
    process.exit(1)
  })
  .catch(err => {
    console.log("\x1b[31m")
    console.log('[ape] Migration failed!')

    if(program.verbose)
      console.log(err)

    console.log()
    process.exit(0)
  })
